# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Tensor Networks for Computer Scientists
author: Markus Wappler, Enterprise Application Development Group, University of Applied Sciences Zittau/Görlitz
logo: img/logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Sphinx extensions
sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    mathjax3_config:
      tex:
        macros:
          C: \mathbb{C}
          F: \mathbb{F}
          Q: \mathbb{Q}
          R: \mathbb{R}
          cU: \mathcal{U}
          cV: \mathcal{V}
          cW: \mathcal{W}
          cH: \mathcal{H}
          cB: \mathcal{B}
          cL: \mathcal{L}
          def: \mathrel{\vcenter{:}}=
          fed: =\mathrel{\vcenter{:}}
          bold: 
            - \pmb{#1}
            - 1
          norm: 
            - \|#1\|
            - 1
          abs: 
            - \lvert#1\rvert
            - 1
          ip: 
            - \langle#1\vert#2\rangle
            - 2
          IP: 
            - \Bigg\langle#1\Bigg\vert#2\Bigg\rangle
            - 2
          tr: \mathrm{tr}
          span: \mathrm{span}          
          inv: \mathrm{inv}
          sgn: \mathrm{sgn}
          id: \mathrm{id}
          diag: \mathrm{diag}
          Diag: \mathrm{Diag}
          swap: \mathrm{SWAP}
          xor: \mathrm{XOR}
          and: \mathrm{AND}
          or: \mathrm{OR}
          copy: \mathrm{COPY}
          red: \text{red}
          green: \text{green}
          blue: \text{blue}

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:  
  url: https://github.com/oremark24/tensor-networks  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

## global substitutions (used for slides layout)
parse:
  myst_substitutions:
    slides: |
      <script>
        const style = document.createElement('style')
        style.type = 'text/css'
        style.innerHTML = `
          @page { 
            size: A4 landscape; 
          }
          h2 {
            page-break-before: always;
          }
          footer {
            display: none;
          }
        `
        document.getElementsByTagName('head')[0].appendChild(style)
      </script>